### ISSUE TITLE
Can I read file from client side?

### ISSUE THREAD

**Issue by tubean** [fonimus/ssh-shell-spring-boot#102]
Hi @fonimus ,
I hope you're doing well. Now I am trying to use the execution via file feature. But it seems we can only use the file on the server host.
I wanna ask you could I use file from client side to use?
Thanks and best regards.

**Comment by fonimus** [comment]
Hello,

If you mean the script command, it is spring shell native command so it uses a local file (on server).
What you can do is uploading your script first with http controller on server location, and then use it in the ssh script command.

**Comment by tubean** [comment]
Hi,
I want to use the local file (via client side) as a batch. But it is ok if you use spring shell native.
I will try another way.
Thanks.
