### ISSUE TITLE
Access to LANG (and other) SSH environment values

### ISSUE THREAD

**Issue by msqr** [fonimus/ssh-shell-spring-boot#104]
I was looking for a way to access the `LANG` environment variable [passed to `SshShellCommandFactory` via a `org.apache.sshd.server.Environment`](https://github.com/fonimus/ssh-shell-spring-boot/blob/1.3.0/starter/src/main/java/com/github/fonimus/ssh/shell/SshShellCommandFactory.java#L109) from the SSH client and [stored as a private `sshEnv` field in `SshShellRunnable`](https://github.com/fonimus/ssh-shell-spring-boot/blob/1.3.0/starter/src/main/java/com/github/fonimus/ssh/shell/SshShellRunnable.java#L81) so I could returned localized messages in my app, but wasn't finding a way to do that.

I was working under some time constrains and ended up extending `SshShellCommandFactory` so I could [capture the SSH environment](https://github.com/SolarNetworkFoundation/snf-accounting-app/blob/0.1.0/common-cli/src/main/java/org/snf/accounting/cli/TrackingSshShellCommandFactory.java#L103) and then [return it later](https://github.com/SolarNetworkFoundation/snf-accounting-app/blob/0.1.0/common-cli/src/main/java/org/snf/accounting/cli/TrackingSshShellCommandFactory.java#L182-L191), which allows me to [get the locale of the client](https://github.com/SolarNetworkFoundation/snf-accounting-app/blob/0.1.0/common-cli/src/main/java/org/snf/accounting/cli/ShellUtils.java#L122-L146). I wondered if you actually had a way to get the SSH environment easily that I missed?

**Comment by fonimus** [comment]
Hello,

You didn't miss anything, you could not get ssh env in the current version.
I added a method in the ssh shell helper in order to retrieve ssh env : https://github.com/fonimus/ssh-shell-spring-boot/#131

It will be available in 1.3.1 release.
In the meantime if you have some time to test it and see if it fits your needs it will be great !

**Comment by msqr** [comment]
Excellent, the change looks great. I will test it out, and if you don't hear anything further from me you can assume it's working for me. Thanks!
