### ISSUE TITLE
[Support Question :) ] How to change default directory for file autocompletion ?

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#109]
Hello!

I know that this is more generic question but i cant figure out how to change the default directory where the @shellMethod tries to find files and provide autocompletion for files. For security reasons I want to set a default directory where user place their scripts and this should not be in project home directory.

Thank you!

**Comment by fonimus** [comment]
Hi,

The completion is managed by the class FileValueProvider which does ``Paths.get("")`` -> so path from which the jar is launched.
I think in your case the best for you would be to implement ``ValueProviderSupport`` (like I did with ``AnyOsFileValueProvider``) and make the completion by yourself ;  so in your case set another base directory and maybe even forbid to go in other directories

**Comment by ThanasisBarekas** [comment]
Thank you very much!
