### ISSUE TITLE
SSH tunneling support

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#110]
Hello again :) 

I am trying to perform ssh tunneling to another machine without exiting ssh-shell but with no success :( is there any feature added or an old one that i miss that i can use? if not is this possible with any other way ?

Thank you very much!
Thanasis

**Comment by fonimus** [comment]
Hello,

By default, ssh server allows only localhost, which is the default value of property `ssh.shell.host`
You can set this property to another value to enable connecting from other host (0.0.0.0 for any host)

**Comment by fonimus** [comment]
Closing this issue, please re-open it if you have other issues.
