### ISSUE TITLE
Optionally hide command groups

### ISSUE THREAD

**Issue by gardenia** [fonimus/ssh-shell-spring-boot#114]
Hi,

At the moment it looks if I configure a command group to be enable=false (e.g. ssh.shell.commands.system.enable=false) that only impacts the availability.  there seems to be no way to hide a command group.  I'd like to be able to optionally hide a command group as (for example) the system commands are too low level for some types of users and only serve to confuse them.

(I realise spring shell in general frown on hiding command groups but I think there is a case for it here and that it can be done in such a way that it doesn't impact existing users who are happy to see everything by default)

is there some way to do this I've missed?

I wrote a basic local patch (see below) to do this with ConditionalOnProperty but rather than overloading the meaning of "enable" I've added an explicit "hide" attribute to CommandProperties (defaulting to false) so no existing users should be impacted unless they want to explicitly use this feature.

So for example setting the attribute:
 ssh.shell.commands.system.hide=true

means "don't show the system command group"

all feedback welcome or alternative suggestions on how to do this.

Thanks.

[ssh_shell_commands_hide2.txt](https://github.com/fonimus/ssh-shell-spring-boot/files/5387551/ssh_shell_commands_hide2.txt)

**Comment by fonimus** [comment]
Hello,

I've added `create` option in command properties, which is binded to spring boot condition to create bean or not, which will make command to not be visible or usable in shell.

You can test the last snapshot, I pushed the feature this morning.
Don't hesitate if you have other comments on this project !

I will make a patch release next week.

**Comment by fonimus** [comment]
Added in release 1.5.2. Closing.

**Comment by gardenia** [comment]
@fonimus : thanks so much for doing this and so quickly.
