### ISSUE TITLE
[Support Request] How to connect to my dockerized ssh-shell-spring-boot service

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#119]
Hello,

I hope you are doing well!
What is the best way to connect through ssh outside a container to the ssh-shell-spring-boot service that is running inside the container ?

Thank you!
Thanasis

**Comment by fonimus** [comment]
Hello,

Yes I'm fine thanks !
I cannot test this right now, but I assume you can just publish the ssh port in the docker file between container and host and set the following configuration in your project :

````yaml
ssh:
  shell:
    host: 0.0.0.0
````

This is the property given to the apache ssh server started within my starter (it means all ip, and is set to localhost by default).

**Comment by ThanasisBarekas** [comment]
It worked! Thank you very much! Merry Xmas
