### ISSUE TITLE
Feature : Allow to hide disable command

### ISSUE THREAD

**Issue by H3llK33p3r** [fonimus/ssh-shell-spring-boot#122]
For clean view, it may be nice to be able, with a configuration, to hide non active command instead of print them with the '*' prefix.

**Comment by fonimus** [comment]
This mechanism comes from spring shell, but since 1.5.2 I added option to completely disable commands :
https://github.com/fonimus/ssh-shell-spring-boot#152

**Comment by H3llK33p3r** [comment]
Ok I understand even if it's not great to be forced to do this manually.
