### ISSUE TITLE
Please enhance the configuration

### ISSUE THREAD

**Issue by H3llK33p3r** [fonimus/ssh-shell-spring-boot#123]
Hi it will be great, if possible that the property `authorized-public-keys-file` becomes a Resource to be able to configure for example authorized keys from a remote hosted file or a package file inside a jar. 

BR.

**Comment by fonimus** [comment]
Good idea, I changed the property to `authorized-public-keys` for a resource (the old property is still available to set a file.
Please find release note [here](https://github.com/fonimus/ssh-shell-spring-boot#154)

**Comment by H3llK33p3r** [comment]
:+1:
