### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#126]
Hello, 

I hope you are doing well. I like to request your support on how exactly this helper.getSshSession().getSessionId(); can be used.
It seems that this return a byte array and not a long number.

Thank you,
Thanasis

**Comment by fonimus** [comment]
Hi,

I'm fine thanks !
This ssh session is an object from library apache mina sshd, I don't really have many knowledge about it so I can't really answer you.
Maybe you can find more info in their documentation : https://mina.apache.org/
