### ISSUE TITLE
[Support] How to obtain password value from SshShellHelper object or SshShellEvent

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#130]
Hello again :) 

I am trying to obtain the password from the objects referenced above. I have tried with this code helper.getAuthentication().getCredentials().toString() but it does not fetch something. I call this from the overidden onEvent(SshShellEvent sshShellEvent) of a SessionListener class that implements SshShellListener.
I need to know the password of the succesful logins.
Is there a way to do this ?

Thank you!
Thanasis

**Comment by fonimus** [comment]
Hello,

There are various ways to connect to ssh (user/password, spring authentication manager, ssh public keys, etc), so in your context it depends on how you connect. In any case I am using provided api (from mina apache ssh project or spring project) so you can look into it to find a way, but I never tried to do so ;).
