### ISSUE TITLE
[Support Request] JavaConnect.java class connects succesfully to ssh app but does not execute commands

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#149]
Hello,

I hope that you are doing well!  
I am trying to create some integration tests for my app that is ssh-shell-spring-boot based.
I used the following code in order to try to execute commands and capture the responses.
https://github.com/fonimus/ssh-shell-spring-boot/blob/master/starter/src/test/java/com/github/fonimus/ssh/shell/JavaConnect.java

Through the JavaConnect.java code I am able to succesfully login to ssh app, I am getting the banner I have configured and the prompt but the command help is not being executed.

Any clue why ?

Thank you!
Thanasis

**Comment by fonimus** [comment]
Hello, sorry for the delay !
I updated the JavaConnect to use PipedInputStream, it appears to solve the problem.
Let me know if you're still struggling with something !

François
