### ISSUE TITLE
1.7.0 maven central

### ISSUE THREAD

**Issue by jlindholm** [fonimus/ssh-shell-spring-boot#173]
Hi, any chance 1.7.0 release could be posted to maven central?

thanks!

**Comment by fonimus** [comment]
Thank you for posting the issue !
It has been uploaded to maven central today, sorry for the delay !

https://repo1.maven.org/maven2/com/github/fonimus/ssh-shell-spring-boot-starter/1.7.0/

**Comment by jlindholm** [comment]
thank you!
