### ISSUE TITLE
[Support Request] BuiltInCommand Script can not be disabled

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#187]
Hello!

I am trying to disable the script built in command. I have successfully managed to disable the help command, but same approach does not seem to work for the other builtInCommands.

I have tried in my main the following :

String[] disabledCommands = {"--spring.shell.command.history.enabled=false"};
String[] fullArgs = StringUtils.concatenateStringArrays(args, disabledCommands);

....

springApplication.run(fullArgs);

The above works for the help command but not for the script.

Do you know maybe why?

Thank you,
Thanasis

**Comment by fonimus** [comment]
Hello !
I re-wrote three commands (history, stacktrace and script) that I didn't put in the properties.
I did that in the release 1.8.0 to come so will be able to deactivate them.
But then it will fall back to spring shell auto configuration that you can deactivate thanks to `spring.shell.command.<name>.enabled` properties

I hope that was what you were looking for :)

**Comment by fonimus** [comment]
1.8.0 should be published in the next minutes/hours
