### ISSUE TITLE
Pasting a command in Linux environment after upgrading to latest version does not work properly

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#254]
Hello,

I hope you are doing well! I have upgraded my project to spring-boot-starter-parent 2.7.5 and ssh-shell-spring-boot-starter to 2.0.2.
I have done changes needed in order to work propely but after testing my app i have found out that pasting commands work as before in windows environments but in linux the app behaves strangely. 
If you paste a command (although it works perfectlty if you write it or if you build it through autocompletion) it does not work until you press enter multiple times. Then after some time it executes the command and prints all these enters.

Is this something known ?

Thank you,
Thanasis

**Comment by marvin-enthus** [comment]
Hi @ThanasisBarekas just seen your issue - we also stumbled over this behavior. It's an issue of the underlying jline3 dependency - i.e. https://github.com/jline/jline3/issues/801 ; Our solution is to set `-Dorg.jline.terminal.jna=false` as java option during startup.

**Comment by ThanasisBarekas** [comment]
Hello,
I tried it and it worked :) Thank you very much and merry X mas!
