### ISSUE TITLE
[Question] How to open ssh connection and immediately execute command

### ISSUE THREAD

**Issue by OS-JaR** [fonimus/ssh-shell-spring-boot#272]
Hi,

did you ever managed to open a ssh connection to your service and immediately execute a command?
In my case, I have a microservice (running in k8s). I want do set up a CronJob, which should do something like
`sshpass --p password ssh -o StrictHostKeyChecking=no me@myk8sapp mycommand`

Even without this CronJob part if I'm trying to connect manually from my terminal (see code block below) the result is the same.
It should open a new ssh connection and run 'mycommand'. But it's not working for me. 

Actually I'm still using version 1.8, and iin this version the result is a continuous exception message and if I'm waiting a bit there we're running OOM

`λ ssh root@127.0.0.1 -p 8022 "help"
Password authentication
Password:

Please type `help` to see available commands
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.`

This is caused 'deep' into 'jline/InteractiveShellApplicationRunner.java:115', where it tries to get the terminals type (which is null -> NPE):
jline/utils/AttributedCharSequence.java:57

`            windows = terminal.getType().toLowerCase(Locale.ENGLISH)
                    .startsWith(AbstractWindowsTerminal.TYPE_WINDOWS);`

If I use your newer release 2.0, there is no NPE anymore in this case, but the command is not executed anyways. Also its 'strange', that the styling is not applied in this case, so if I connection 'normally' there is tab completion, highliting and styling (e.g. red text if command is misspelled), but if I connection with inital command then this command is not executed, and other features like tab completion and highlighting/styles are not working.

Have you any idea how to solve this?

Thanks,
Jan

**Comment by fonimus** [comment]
Hello @OS-JaR, I am sorry but I have no idea how to solve this, but if you find something I will be happy to fix my code if there is any issue preventing you to achieve your goal !
