### ISSUE TITLE
[Support Request] How to disable CBC mode cipher encryption in Apache Mina SSHD Java library

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#299]
hello,

I hope you are doing well. I like to ask you if there is way to disable the cbc mode cipher encryption in Apache Mina SSHD Java library used in ssh-shell-spring-boot.

This can be done like this 

SshServer sshServer = SshServer.setUpDefaultServer();
ServerBuilder serverBuilder = sshServer.builder();
List<String> ciphers = serverBuilder.ciphers();
ciphers.removeIf(cipher -> cipher.contains("/cbc/"));
sshServer.setServerBuilder(serverBuilder);
sshServer.start();

Is there a way to expose the server used in your library (https://github.com/fonimus/ssh-shell-spring-boot/blob/main/starter/src/main/java/com/github/fonimus/ssh/shell/SshShellConfiguration.java)
and add the above configuration ?

Thank you
Thanasis

**Comment by fonimus** [comment]
You're welcome ! ;)
