### ISSUE TITLE
[Support Request] sessionId vs getIoSession().getId()

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#305]
Hello!

What is the difference between the sshShellEvent.getSessionId() from com.github.fonimus.ssh.shell.listeners.SshShellEvent and the getSshSession().getIoSession().getId() from the com.github.fonimus.ssh.shell.SshShellHelper ?

Both of them give the same number (for example 101 for the first user that logins to ssh).

Are these always the same ?
Thank you!

**Comment by fonimus** [comment]
Hello @ThanasisBarekas, yes there will always be the same, it is the ssh session identifier which comes from `sshd` library. If you look at the source code in class `SshShellEvent` I am calling the following (it is just a shortcut to access event session id):
````
public long getSessionId() {
    return session.getServerSession().getIoSession().getId();
}
````

**Comment by ThanasisBarekas** [comment]
Thank you, Have a nice week!
