### ISSUE TITLE
IOException and WindowClosedException are thrown and the ssh shell is hanged when the user quit ssh shell

### ISSUE THREAD

**Issue by Cepr0** [fonimus/ssh-shell-spring-boot#57]
We are trying to use **ssh-shell-spring-boot** in our project but faced with the following situation - when we exit from the ssh shell (with commands 'quit' or 'exit') then the application throws exception `java.io.IOException`. 

When we start the second ssh shell and quit it, then application throws `org.apache.sshd.common.channel.WindowClosedException`. 

Moreover, when we try to quit the first ssh shell then it **hangs** and application throws `java.io.IOException` with message 'Stream Closed'. 

In addition, after these exceptions, if we resize the terminal window then application logs warning messages: 
> StandardEnvironment      : Failed (LastErrorException) to signal WINCH to listener=com.github.fonimus.ssh.shell.SshShellCommandFactory$$Lambda$653/1512951254@4930b272: [9] Bad file descriptor

Please see the attached screencast for details.

These exceptions are thrown on Linux environment. On Windows they are not thrown but shell hangs as well.

![ssh-shell-sp-parent-demo](https://user-images.githubusercontent.com/10778600/60084453-3c7c7000-9740-11e9-8ca2-f39542b3478e.gif)

**Comment by fonimus** [comment]
Hello, 

Thank you for posting issue !

I am developping on mac os environment, and can test it easily on windows, and don't have those issues. What is your linux environment ?

I am not sure to be able to reproduce/work on it on linux, but I would be happy to look at any merge request you could send me !

**Comment by fonimus** [comment]
Hello,

I finally had some time to test it on ubuntu platform.
I was able to reproduce your issues and fixed the hanging issues when multiple terminal are used at the same time.
The IOException is still happening when quitting terminal, but only on linux (ubuntu at least) with a printStacktrace in the terminal code.. (so I cannot remove it unfortunately) and I am not sure why it does.

The version 1.2.0 fixes the issue (at least on ubuntu) : https://github.com/fonimus/ssh-shell-spring-boot/releases/tag/1.2.0.
