### ISSUE TITLE
Different thread per ssh connection

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#75]
Hello, 

Thank you for this great library :) I would like to request your help on how to configure the basic demo in way, so that different thread handles each ssh connection.

Thank you very much,
Thanasis

**Comment by fonimus** [comment]
Hello

Since 1.2.0, all ssh connections are already handled in different threads.
If you add a log in a command and take a look at application logs you should see it :

````
2019-11-10 11:02:05.677  INFO 11522 --- [ssh-session-114931289759453] c.g.fonimus.ssh.shell.basic.DemoCommand  : A log from command
2019-11-10 11:02:08.102  INFO 11522 --- [ssh-session-114935767040744] c.g.fonimus.ssh.shell.basic.DemoCommand  : A log from command
````

François

**Comment by ThanasisBarekas** [comment]
Thank you very much for your quick response, this library is very useful and a must add on for spring-shell.

**Comment by ThanasisBarekas** [comment]
Hello, 
I have tried to add a counter at the DemoCommand.java file in order to increase it every time pojo command is being given. The counter value is provided by echo command.
I have opened 2 ssh connections. In second connection counter was increased to 2 but when interogated the value from the other session it was also 2. I used the following version as you instructed :
              <dependency>
		<groupId>com.github.fonimus</groupId>
			<artifactId>ssh-shell-spring-boot-starter</artifactId>
			<version>1.2.0</version>
		</dependency>	
Attached you find also the file.

[DemoCommand.txt](https://github.com/fonimus/ssh-shell-spring-boot/files/3831041/DemoCommand.txt)

Is it normal that the value is increased through different ssh sessions ?

Thank you,
Thanasis

**Comment by ThanasisBarekas** [comment]
Actually to be more precise I would like to implement a mechanism so that every ssh connection can have its own state for example. For example in the file I shared in previous comment each ssh connection should have its own value of counter connected. 
Is there a sophisticated way to implement this ? My idea is to use the unique [ssh-session-114931289759453] id to map this id with counter value. How can I get this id from code?

Thank you very much in advance,
Thanasis

**Comment by fonimus** [comment]
Hello,

The command `@SshShellComponent` is a spring singleton **@Component (bean)**, so each thread call the same instance of the command.

If you want to retrieve this id, it is simply the thread name :

````
LOGGER.info("{}", Thread.currentThread().getName());
ssh-session-243348967136309
````

If you want to share some stuff for one connection, you could use a `java.lang.ThreadLocal`

**Comment by ThanasisBarekas** [comment]
Hello,

I have managed to implement a session manager to keep some data per ssh connection using the Thread.currentThread().getId() as key. 

Thank you very much or your support,
Thanasis
