### ISSUE TITLE
How to get the username inside a shellMethod

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#77]
Hello again and sorry for raising another issue :)
I am trying to get the username of the user that is connected inside a shell method. 
I am using a  custom authentication bean @Bean("customAuthManager") similar to the one you used in the complete example.
Question 1) How can i get the username inside a shell method ?
Question 2) New users (manager.createUser(User.withUsername("user").password(encoder.encode("thanasis")).roles("USER").build()); ) can be created only on application startup or they can be created dynamically also later in app lifecycle ?

Thank you very much

**Comment by fonimus** [comment]
Hello,

For the first part, you have the method `com.github.fonimus.ssh.shell.SshShellHelper#getAuthentication` which provides you the authenticated information (principal, authorities, etc).

For the second part, the new users created in the DemoSecurity are just an example, based on in memory user details manager provided by spring boot.
You should use your own user details manager (see spring boot documentation) with database for instance, and then you can even use the ssh shell to create, list, delete users, etc

**Comment by ThanasisBarekas** [comment]
Thank you very much for your support!

**Comment by fonimus** [comment]
You're welcome !
