### ISSUE TITLE
Local shell disappearing when adding ssh shell

### ISSUE THREAD

**Issue by JRoviraa** [fonimus/ssh-shell-spring-boot#78]
**Description:**
The local shell is not usable when adding the ssh shell dependency

**How to reproduce:**

Have both these dependencies on your project:

```
<dependency>
    <groupId>com.github.fonimus</groupId>
    <artifactId>ssh-shell-spring-boot-starter</artifactId>
    <version>1.1.6</version>
</dependency>
<dependency>
    <groupId>org.springframework.shell</groupId>
    <artifactId>spring-shell-starter</artifactId>
    <version>2.0.1.RELEASE</version>
</dependency>
```

Then try to use the local shell, it will not work, but the remote shell will. If you remove the ssh shell dependency it will still work

**Comment by fonimus** [comment]
Hello, it is kind of the point :)
As I want to connect to ssh to it, I did not want to have the prompt in local.

Would you be interested by adding property to let the prompt as in spring shell ?

**Comment by JRoviraa** [comment]
Yes, it would be great to be able to use it locally and also remotely!

**Comment by fonimus** [comment]
I pushed functionality with new property to set for you : ``ssh.shell.prompt.local.enable``

Can you test it with master branch on your side before I make a release ?

**Comment by JRoviraa** [comment]
Thanks a lot, it works as expected. Let me know when your release it!

**Comment by fonimus** [comment]
You're welcome.
Version 1.2.1 released (you'll have to wait a bit until it's on maven central)
