### ISSUE TITLE
[Help] How to force shutdown session by sessionId?

### ISSUE THREAD

**Issue by tubean** [fonimus/ssh-shell-spring-boot#94]
Hi @fonimus ,
Thank you very much for your advice.
Now I am facing a problems about managing sessions. I have to develop an managing feature for administrator, which can show all active sessions and can force shutdown them by their id.
Could you tell me which class can handle this action?
I am looking forward to hearing from you. Thanks a lot.

**Comment by fonimus** [comment]
Hi,

There is a component managing sessions, but mainly to log start/stop etc.
I will try to work on a manager to do such things which you could inject in your application.

**Comment by fonimus** [comment]
I wrote a session manager, please check the doc and see if it suits your needs : https://github.com/fonimus/ssh-shell-spring-boot#session-manager

**Comment by tubean** [comment]
Hi,
It worked perfectly 😄 
Many thanks.
