### ISSUE TITLE
History file was shared for all users?

### ISSUE THREAD

**Issue by tubean** [fonimus/ssh-shell-spring-boot#96]
Hi @fonimus ,
Sorry if I bothered you. When I use the history command, I expected all commands which I had typed in this session or this account will be shown. But it's not working like that. If you use another account (ex. user), you can see everything what the admin type before. (All of history was stored in sshShellHistory file.
I don't think it is right when we shared this information for all users. 
What do you think about this case?

**Comment by fonimus** [comment]
Hello,

It is very interesting indeed, I did not even think of it as it is handled by spring shell natively in single file, but I did the dev and you can test it on master branch if you like.

To not impact already existing projects I added a new conf : ``ssh.shell.shared-history=true`` by default. Juste set it to false and optionally specify ``ssh.shell.history-directory``

**Comment by tubean** [comment]
Hi,
I updated your code, it already has generated a file per user. But when I use 'history' command, nothing shown on console.
Could you give me an advice?
Thanks.

**Comment by fonimus** [comment]
Hi, the history command was the spring shell default, so not loading the new file I implemented.
I overrided the default history command with my own, it should work now.

**Comment by tubean** [comment]
Hi, it works. Thank you so much 🙇‍♂️
