### ISSUE TITLE
[Exception] NumberFormatException: null

### ISSUE THREAD

**Issue by tubean** [fonimus/ssh-shell-spring-boot#98]
Hi @fonimus ,
I am using your library to build a Spring Shell and it was very good when I used SSH tool like Putty to connect my Shell.

But when I build another Java app as SSH client, follows this [tutorial](https://www.journaldev.com/246/jsch-example-java-ssh-unix-server) , I got an Exception "java.lang.NumberFormatException" at class SshShellRunnable.

It seems you want to detect size of client's tool, but when I build Java app, there is no size for that.

Could you give me an advice?

Thanks and best regards.

**Comment by fonimus** [comment]
Hello,

I am also using jsch in my tests, but with channel named `shell`

Example:

````java
JSch jsch = new JSch();
Session session = jsch.getSession(user, host, port);
session.setPassword(pass);
Properties config = new Properties();
config.put("StrictHostKeyChecking", "no");
session.setConfig(config);
session.connect();
Channel channel = session.openChannel("shell");
PipedInputStream pis = new PipedInputStream();
PipedOutputStream pos = new PipedOutputStream();
channel.setInputStream(new PipedInputStream(pos));
channel.setOutputStream(new PipedOutputStream(pis));
channel.connect();

// then write in outputstream and read from inputstream
````

Also I pushed a patch which does not fail when I cannot get terminal size, but I don't know if you won't have other problems then with this exec channel (I am not very familiar with this library).

**Comment by tubean** [comment]
Thanks for your support :D
